apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-nginx
  namespace: ${IMAGE_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ${APPLICATION_FQDN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
           service:
             name: simple-nginx
             port:
              number: 80

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: simple-nginx
#   namespace: ${IMAGE_NAMESPACE}
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
# #    cert-manager.io/cluster-issuer: "letsencrypt-staging"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   tls:
#   - hosts:
#     - ${APPLICATION_FQDN}
#     secretName: simple-nginx-jnlp-tls
#   rules:
#   - host: ${APPLICATION_FQDN}
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: simple-nginx
#             port:
#               number: 80